### ISSUE TITLE
Readme build steps result in error

### ISSUE THREAD

**Issue by benduran** [openwebf/quickjs#49]
Hi everyone! I wanted to open a ticket, as I'm hoping to leverage the improvements to QuickJS that you all have graciously made. However, when attempting to follow the build steps in the Readme, I am greeted with the following error:

```
CMake Error at CMakeLists.txt:20 (add_subdirectory):
  The source directory

    /Users/bduran/devlop/opensource/quickjs/vendor/mimalloc

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

## Reproduction Video on Fresh clone

![CleanShot 2023-07-20 at 12 08 19](https://github.com/openwebf/quickjs/assets/6392223/ecb0e1db-2cc2-445d-a6ed-8f6c52083c12)

I'm guess there might be a missing step in the Readme's [How to Build](https://github.com/openwebf/quickjs#how-to-build) instructions. Could you all advise on what's missing?

Thanks!

**Comment by kyaru92** [comment]
you should clone this repo with --recursive
```bash
git clone --recursive https://github.com/openwebf/quickjs.git
```
mimalloc is a submodule

**Comment by benduran** [comment]
Thanks @kyaru92! I submitted a PR to update the Readme with these instructions. You can review this here: https://github.com/openwebf/quickjs/pull/50

thanks!
